In [3]:
import numpy as np
import pandas as pd

In [4]:
outlook=['sunny','sunny','overcast','rainy','rainy','rainy',
         'overcast','sunny','sunny','rainy','sunny',
         'overcast','overcast','rainy']
temperature=['hot','hot','hot','mild','cool','cool','cool','mild',
             'cool','mild','mild','mild','hot','mild']
humidity=['high','high','high','high','normal','normal',
          'normal','high','normal','normal','normal','high','normal','high']

wind=['weak','strong','weak','weak','weak','strong','strong','weak',
      'weak','weak','strong','strong','weak','strong']

play=['no','no','yes','yes','yes','no','yes','no','yes','yes',
      'yes','yes','yes','no']

In [5]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
outlook_enc = lb.fit_transform(outlook)
temp_enc = lb.fit_transform(temperature)
hum_enc = lb.fit_transform(humidity)
wind_enc = lb.fit_transform(wind)

In [6]:
outlook_enc


array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [7]:
temp_enc

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [8]:
hum_enc

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [9]:
wind_enc

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [10]:
fea = list(zip(outlook_enc,temp_enc,hum_enc,wind_enc))
fea

[(2, 1, 0, 1),
 (2, 1, 0, 0),
 (0, 1, 0, 1),
 (1, 2, 0, 1),
 (1, 0, 1, 1),
 (1, 0, 1, 0),
 (0, 0, 1, 0),
 (2, 2, 0, 1),
 (2, 0, 1, 1),
 (1, 2, 1, 1),
 (2, 2, 1, 0),
 (0, 2, 0, 0),
 (0, 1, 1, 1),
 (1, 2, 0, 0)]

In [11]:
from sklearn.naive_bayes import MultinomialNB
ml = MultinomialNB()
ml.fit(fea,play)


MultinomialNB()

In [12]:
pr = ml.predict([[2,0,0,0]])
pr

array(['no'], dtype='<U3')

TypeError: ignored